name = 'Theme name'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = https://github.com/Flowers2Algernon/hugo-fullstacker

# If you have a running demo of the theme
demosite = https://flowers2algernon.github.io/hugo-fullstacker/

# Taxonomy terms
tags = ['blog', 'personal', 'portfolio']
features = ['some', 'awesome', 'features']

[author]
  name = Jinhong Zhu
  homepage = 'Your website'

